#!/bin/sh

wget ftp://ftp.perforce.com/perforce/r15.1/bin.linux26x86_64/p4d
chmod +x p4d
sudo mv p4d /usr/local/bin
sudo mkdir /version_control/perforce
sudo chown mirsad /version_control/perforce
sudo mkdir /var/log/perforce
sudo chown mirsad /var/log/perforce
sudo apt-get install daemon
cd /etc/init.d
wget https://github.com/dinoDuvnjak/linux-perforce-installer/blob/master/p4dservice
chmod +x /etc/init.d/p4dservice
sudo update-rc.d p4dservice defaults
sudo reboot
